server:
  port: 8002

spring:
  rabbitmq:
    addresses: 192.168.31.62:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual    # 手工签收
        concurrency: 5
        max-concurrency: 10