server:
  port: 8001

spring:
  rabbitmq:
    addresses: 192.168.31.62:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true    # confirm模式
    publisher-returns: true     # return机制
    template:
      mandatory: true           # 与return机制结合配置次属性
